version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: circleci/node:latest
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Running Server and Cypress
          command: npm run test:ci
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
